In [1]:
import sys
from pathlib import Path

sys.path.append(str(Path.cwd().parent / "data"))
sys.path.append(str(Path.cwd().parent / "bayesian_order_based_learning"))

In [2]:
import scipy.io
import pandas as pd
import numpy as np
import networkx as nx
import os
import re

In [3]:
data_path_rel = os.path.join(Path.cwd().parent, "data")

gene_matrix = scipy.io.mmread(os.path.join(data_path_rel, "GSE144136_GeneBarcodeMatrix_Annotated.mtx"))
gene_matrix = gene_matrix.tocsr()

gene_names = pd.read_csv(os.path.join(data_path_rel, "GSE144136_GeneNames.csv"))
gene_names.set_index('Unnamed: 0', inplace=True)
cell_names = pd.read_csv(os.path.join(data_path_rel, "GSE144136_CellNames.csv"))
cell_names.set_index('Unnamed: 0', inplace=True)

gene_df = pd.DataFrame.sparse.from_spmatrix(gene_matrix, index=gene_names["x"], columns=cell_names["x"])

In [4]:
gene_list = pd.read_excel(os.path.join(data_path_rel, "41593_2020_621_MOESM3_ESM.xlsx"), sheet_name="Supplementary Table 32", header=2)

top_41_genes = gene_list[gene_list["FDR"] < 0.1]
top_41_genes["idx"] = range(len(top_41_genes))

/var/folders/nv/0gm0y9v14g5442csxys2r93h0000gn/T/ipykernel_38365/2222079740.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  top_41_genes["idx"] = range(len(top_41_genes))

In [5]:
constrained_gene_df = gene_df[gene_df.index.isin(top_41_genes["Gene"])]
constrained_gene_df_idx = constrained_gene_df.rename(index=dict(zip(top_41_genes["Gene"], top_41_genes["idx"])))
constrained_gene_df_idx = constrained_gene_df_idx.sort_index(axis=0)

In [6]:
def get_patient(cell_name):
    return re.search(r'\.(\d+)_(?:Suicide|Control)_B\d+', cell_name).group(1)

patient_dfs = []

for patient_num, patient_df in constrained_gene_df_idx.T.groupby(get_patient):
    patient_dfs.append((int(patient_num), patient_df))

In [7]:
patient_dfs.sort()

In [8]:
len(patient_dfs)

34

In [9]:
# 24
patient_dfs[24][1]

x,0,1,2,3,4,5,6,7,8,9,...,31,32,33,34,35,36,37,38,39,40
x,,,,,,,,,,,,,,,,,,,,,
Astros_2.25_Control_B3_AAACGGGCAAATCCGT,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Astros_2.25_Control_B3_AAAGATGTCCATGCTC,0,0,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Ex_3_L4_5.25_Control_B3_AAGGCAGCATCGTCGG,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
Ex_10_L2_4.25_Control_B3_AAGTCTGAGCCACTAT,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Ex_10_L2_4.25_Control_B3_ACACTGACACTAAGTC,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Astros_2.25_Control_B5_TTCTTAGAGCCAACAG,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
Ex_10_L2_4.25_Control_B5_TTCTTAGAGTGGAGTC,0,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Ex_10_L2_4.25_Control_B5_TTGCCGTGTCTAGTCA,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Ex_5_L5.25_Control_B5_TTGGAACAGCCATCGC,1,0,0,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,1
Inhib_2_VIP.25_Control_B5_TTTGTCACAATAACGA,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [10]:
constrained_gene_df

x,Ex_10_L2_4.3_Control_B3_AAACCTGAGGTAGCCA,Inhib_5.3_Control_B3_AAACCTGCAAACTGTC,Ex_10_L2_4.3_Control_B3_AAACCTGCAACAACCT,Ex_8_L5_6.3_Control_B3_AAACCTGGTCCGAACC,Inhib_2_VIP.3_Control_B3_AAACCTGGTCGTGGCT,Mix_2.3_Control_B3_AAACGGGAGGAACTGC,Oligos_3.3_Control_B3_AAACGGGAGTGGTAGC,Ex_7_L4_6.3_Control_B3_AAACGGGAGTGTGAAT,Astros_3.3_Control_B3_AAACGGGCATCCAACA,Ex_5_L5.3_Control_B3_AAACGGGGTATTCGTG,...,Inhib_5.17_Suicide_B1_TTTGCGCTCGGCTTGG,Ex_10_L2_4.17_Suicide_B1_TTTGGTTCAGTCCTTC,Inhib_6_SST.17_Suicide_B1_TTTGGTTGTCCAGTGC,Ex_10_L2_4.17_Suicide_B1_TTTGGTTTCTGTCCGT,Micro/Macro.17_Suicide_B1_TTTGTCAAGATGTCGG,OPCs_1.17_Suicide_B1_TTTGTCAAGCTCCTTC,Ex_10_L2_4.17_Suicide_B1_TTTGTCAAGGCTAGCA,Ex_10_L2_4.17_Suicide_B1_TTTGTCAAGGGATGGG,Inhib_2_VIP.17_Suicide_B1_TTTGTCACATGTCCTC,Inhib_7_PVALB.17_Suicide_B1_TTTGTCAGTAAGTGGC
x,,,,,,,,,,,,,,,,,,,,,
KAZN,1,1,1,0,2,0,1,2,0,0,...,3,0,1,1,3,0,1,0,4,2
PINK1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
ARL8A,0,0,0,0,0,0,0,0,0,1,...,0,0,0,1,0,0,0,0,0,0
ADORA1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
KIF26B,0,0,1,0,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
AC133680.1,0,0,0,0,0,0,0,0,0,0,...,1,0,0,0,2,0,0,0,0,0
ACAA1,0,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
CAMK2N2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
HIVEP1,0,0,0,0,0,0,0,0,0,0,...,1,0,0,0,1,0,1,0,0,0
TAPBP,1,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
GRM4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
PRKAR1B,0,1,0,0,0,0,0,2,0,0,...,0,0,0,0,0,0,0,1,0,1
DOCK4,2,0,0,5,0,0,0,0,1,0,...,0,0,0,1,0,0,0,0,0,1
TMSB4X,1,0,0,0,1,0,0,1,0,0,...,0,0,2,0,0,0,0,1,0,0
PRAF2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
TCEAL2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
TUBB4B,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
CEND1,0,2,0,1,0,0,0,0,0,0,...,0,0,0,0,1,0,0,1,0,1
TMEM132A,0,0,1,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,1
FADS2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
NRXN2,3,0,1,1,0,0,0,2,0,0,...,0,0,0,0,1,0,1,0,0,0
KLC2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,2
PPME1,0,1,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,2,0,0,0
CAMK1D,4,1,1,0,0,0,0,1,1,0,...,1,1,1,1,2,0,0,3,0,0
CISD1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
FAM66C,0,0,0,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0
PEBP1,1,1,1,0,0,0,0,0,1,1,...,0,0,0,0,0,0,1,0,0,1
TSC22D1,3,0,0,0,0,0,0,3,0,0,...,3,0,1,2,0,0,1,0,0,0
HSP90AA1,0,0,0,0,1,0,0,0,0,1,...,0,0,0,1,0,0,1,3,0,1
GRIN2A,1,0,2,1,0,0,1,1,0,1,...,1,0,0,1,4,0,1,3,1,4
ALDOA,1,0,0,0,0,0,0,0,0,1,...,0,0,0,1,0,0,0,1,0,0
ZBTB4,0,0,0,0,0,0,0,0,2,0,...,0,0,0,0,0,0,0,0,0,0
TOM1L1,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
MAP2K7,0,0,1,0,1,0,0,1,0,1,...,0,0,0,0,0,0,0,0,0,0
RAB11B,0,0,0,0,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
CCDC130,1,0,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,1
ZFP36,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
RPS11,0,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
PTOV1,1,0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
SEZ6L,0,1,1,0,1,0,0,0,0,1,...,0,0,0,0,1,0,1,0,0,0
APP,1,2,2,2,0,0,0,4,0,0,...,0,0,0,5,0,0,3,2,0,2

In [11]:
constrained_gene_df_idx

x,Ex_10_L2_4.3_Control_B3_AAACCTGAGGTAGCCA,Inhib_5.3_Control_B3_AAACCTGCAAACTGTC,Ex_10_L2_4.3_Control_B3_AAACCTGCAACAACCT,Ex_8_L5_6.3_Control_B3_AAACCTGGTCCGAACC,Inhib_2_VIP.3_Control_B3_AAACCTGGTCGTGGCT,Mix_2.3_Control_B3_AAACGGGAGGAACTGC,Oligos_3.3_Control_B3_AAACGGGAGTGGTAGC,Ex_7_L4_6.3_Control_B3_AAACGGGAGTGTGAAT,Astros_3.3_Control_B3_AAACGGGCATCCAACA,Ex_5_L5.3_Control_B3_AAACGGGGTATTCGTG,...,Inhib_5.17_Suicide_B1_TTTGCGCTCGGCTTGG,Ex_10_L2_4.17_Suicide_B1_TTTGGTTCAGTCCTTC,Inhib_6_SST.17_Suicide_B1_TTTGGTTGTCCAGTGC,Ex_10_L2_4.17_Suicide_B1_TTTGGTTTCTGTCCGT,Micro/Macro.17_Suicide_B1_TTTGTCAAGATGTCGG,OPCs_1.17_Suicide_B1_TTTGTCAAGCTCCTTC,Ex_10_L2_4.17_Suicide_B1_TTTGTCAAGGCTAGCA,Ex_10_L2_4.17_Suicide_B1_TTTGTCAAGGGATGGG,Inhib_2_VIP.17_Suicide_B1_TTTGTCACATGTCCTC,Inhib_7_PVALB.17_Suicide_B1_TTTGTCAGTAAGTGGC
x,,,,,,,,,,,,,,,,,,,,,
0,1,0,0,0,1,0,0,1,0,0,...,0,0,2,0,0,0,0,1,0,0
1,0,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,1,1,1,0,2,0,1,2,0,0,...,3,0,1,1,3,0,1,0,4,2
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
5,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
6,3,0,1,1,0,0,0,2,0,0,...,0,0,0,0,1,0,1,0,0,0
7,0,0,1,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,1
8,1,0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
9,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
10,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
11,0,0,0,0,0,0,0,0,0,0,...,1,0,0,0,2,0,0,0,0,0
12,0,0,0,0,0,0,0,0,0,1,...,0,0,0,1,0,0,0,0,0,0
13,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
14,3,0,0,0,0,0,0,3,0,0,...,3,0,1,2,0,0,1,0,0,0
15,0,0,0,0,1,0,0,0,0,1,...,0,0,0,1,0,0,1,3,0,1
16,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
17,0,0,1,0,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
18,0,0,0,0,0,0,0,0,2,0,...,0,0,0,0,0,0,0,0,0,0
19,1,0,2,1,0,0,1,1,0,1,...,1,0,0,1,4,0,1,3,1,4
20,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
21,4,1,1,0,0,0,0,1,1,0,...,1,1,1,1,2,0,0,3,0,0
22,2,0,0,5,0,0,0,0,1,0,...,0,0,0,1,0,0,0,0,0,1
23,0,0,0,0,0,0,0,0,0,0,...,1,0,0,0,1,0,1,0,0,0
24,0,0,0,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0
25,1,0,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,1
26,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
27,0,1,0,0,0,0,0,2,0,0,...,0,0,0,0,0,0,0,1,0,1
28,0,0,0,0,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
29,0,2,0,1,0,0,0,0,0,0,...,0,0,0,0,1,0,0,1,0,1
30,1,2,2,2,0,0,0,4,0,0,...,0,0,0,5,0,0,3,2,0,2
31,0,1,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,2,0,0,0
32,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
33,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
34,1,1,1,0,0,0,0,0,1,1,...,0,0,0,0,0,0,1,0,0,1
35,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,2
36,0,1,1,0,1,0,0,0,0,1,...,0,0,0,0,1,0,1,0,0,0
37,1,0,0,0,0,0,0,0,0,1,...,0,0,0,1,0,0,0,1,0,0
38,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
39,0,0,1,0,1,0,0,1,0,1,...,0,0,0,0,0,0,0,0,0,0
40,1,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [12]:
top_41_genes

,Gene,Estimate,Std. Error,df,t value,Pr(>|t|),Fold Change,FDR,Cluster,idx
0,TMSB4X,-0.401627,0.065789,646.000000,-6.104766,1.776243e-09,0.669231,0.000154,Astro3,0
1,ACAA1,-0.113096,0.018823,962.561266,-6.008367,2.655221e-09,0.893065,0.000154,Ex7,1
2,RPS11,-0.080013,0.014327,3368.000000,-5.584886,2.524009e-08,0.923105,0.000977,Ex7,2
3,KAZN,0.485059,0.095822,263.275306,5.062061,7.799085e-07,1.624271,0.021070,OPC2,3
4,PRAF2,-0.061566,0.012332,383.242170,-4.992326,9.074639e-07,0.940291,0.021070,Ex3,4
5,GRM4,-0.099405,0.020775,1625.000000,-4.784921,1.865614e-06,0.905376,0.029844,Ex8,5
6,NRXN2,-0.183301,0.038823,1434.951257,-4.721444,2.570690e-06,0.832518,0.029844,In1,6
7,TMEM132A,-0.106942,0.022638,2280.250645,-4.723975,2.453433e-06,0.898578,0.029844,In2,7
8,PTOV1,-0.109207,0.022719,2825.999973,-4.806804,1.613831e-06,0.896545,0.029844,In2,8
9,TCEAL2,-0.253221,0.052822,521.144045,-4.793852,2.137576e-06,0.776297,0.029844,In8,9
10,CISD1,-0.124401,0.026061,246.254899,-4.773503,3.107430e-06,0.883025,0.032796,Ex6,10
11,AC133680.1,-0.062666,0.013541,2478.565142,-4.627970,3.882915e-06,0.939257,0.037566,Ex3,11
12,ARL8A,-0.167269,0.036313,2098.148437,-4.606298,4.344775e-06,0.845972,0.038801,Ex2,12
13,FADS2,-0.308353,0.067667,646.000000,-4.556939,6.207441e-06,0.734656,0.040630,Astro3,13
14,TSC22D1,-0.519194,0.112459,375.436457,-4.616737,5.361120e-06,0.595000,0.040630,OPC2,14
15,HSP90AA1,-0.472723,0.103617,366.477784,-4.562217,6.914442e-06,0.623303,0.040630,OPC2,15
16,ADORA1,-0.072023,0.015806,876.257245,-4.556792,5.930614e-06,0.930509,0.040630,Ex7,16
17,KIF26B,0.133129,0.029415,661.015726,4.525904,7.131547e-06,1.142397,0.040630,In2,17
18,ZBTB4,-0.107747,0.023668,1269.989729,-4.552395,5.812578e-06,0.897855,0.040630,In2,18
19,GRIN2A,0.404221,0.088511,337.000000,4.566919,6.950021e-06,1.498135,0.040630,Endo,19
20,ZFP36,-0.400972,0.088039,337.000000,-4.554461,7.349402e-06,0.669669,0.040630,Endo,20
21,CAMK1D,0.186366,0.042085,1678.000000,4.428287,1.011160e-05,1.204863,0.053359,OPC1,21
22,DOCK4,0.396721,0.089130,413.510876,4.451052,1.100455e-05,1.486941,0.054570,Astro3,22
23,HIVEP1,-0.288550,0.065037,473.000000,-4.436732,1.137311e-05,0.749349,0.054570,OPC2,23
24,FAM66C,0.100497,0.022876,2020.000000,4.393136,1.175113e-05,1.105721,0.054570,In6,24
25,CCDC130,-0.084043,0.019387,2891.010036,-4.335109,1.506646e-05,0.919392,0.067275,In5,25
26,CAMK2N2,-0.210203,0.048348,574.000000,-4.347661,1.627971e-05,0.810420,0.070000,In8,26
27,PRKAR1B,-0.191870,0.044720,2093.092578,-4.290486,1.864014e-05,0.825414,0.074622,Ex2,27
28,RAB11B,-0.189640,0.043910,594.255493,-4.318799,1.838299e-05,0.827257,0.074622,In3,28
29,CEND1,-0.124181,0.029325,1677.999997,-4.234578,2.413917e-05,0.883220,0.084922,OPC1,29
30,APP,0.093319,0.021988,959.675873,4.244010,2.408606e-05,1.097812,0.084922,Ex3,30
31,PPME1,-0.126043,0.029682,1269.247936,-4.246505,2.329608e-05,0.881577,0.084922,Ex8,31
32,PINK1,-0.111154,0.021506,25.722759,-5.168498,2.222235e-05,0.894801,0.084922,In5,32
33,TUBB4B,-0.152098,0.027170,18.083213,-5.598080,2.549849e-05,0.858904,0.087066,Ex6,33
34,PEBP1,-0.492882,0.085039,15.906045,-5.795959,2.795817e-05,0.610863,0.090033,OPC2,34
35,KLC2,-0.166116,0.039414,627.000000,-4.214658,2.869391e-05,0.846948,0.090033,In3,35
36,SEZ6L,-0.347470,0.082261,491.550796,-4.223981,2.860905e-05,0.706473,0.090033,In8,36
37,ALDOA,-0.323963,0.077143,398.695301,-4.199535,3.301877e-05,0.723277,0.097588,OPC2,37
38,TOM1L1,0.342587,0.081809,473.000000,4.187665,3.362359e-05,1.408588,0.097588,OPC2,38
39,MAP2K7,-0.065523,0.015707,1216.264683,-4.171525,3.240589e-05,0.936578,0.097588,Ex7,39
40,TAPBP,-0.078599,0.015454,23.572321,-5.085892,3.517559e-05,0.924411,0.099603,Ex10,40

In [13]:
X = []
for _, pat_k in patient_dfs:
    X.append(pat_k.to_numpy())

In [14]:
X[0]

array([[2, 0, 0, ..., 0, 0, 0],
       [9, 1, 1, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [3, 0, 1, ..., 0, 0, 1],
       [0, 0, 0, ..., 0, 0, 0],
       [2, 0, 0, ..., 1, 0, 0]], shape=(3267, 41))

In [15]:
patient_dfs[0][1]

x,0,1,2,3,4,5,6,7,8,9,...,31,32,33,34,35,36,37,38,39,40
x,,,,,,,,,,,,,,,,,,,,,
Ex_2_L5.1_Suicide_B5_AAACCTGAGGACAGCT,2,0,0,0,0,0,0,2,1,0,...,0,1,1,2,0,1,3,0,0,0
Ex_3_L4_5.1_Suicide_B5_AAACCTGAGGCCCTTG,9,1,1,1,1,0,1,0,1,1,...,2,1,3,8,0,0,5,0,0,0
Inhib_1.1_Suicide_B5_AAACCTGCATTCCTCG,0,0,0,2,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
Ex_1_L5_6.1_Suicide_B5_AAACCTGGTCGAGTTT,2,0,0,0,0,0,0,0,1,1,...,0,0,0,1,1,0,0,1,0,1
Ex_3_L4_5.1_Suicide_B5_AAACCTGTCATGTCTT,3,0,0,1,0,0,3,0,0,1,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Ex_3_L4_5.1_Suicide_B5_TTTGTCAGTAGCAAAT,1,0,0,2,0,0,0,1,0,0,...,1,0,0,2,0,1,0,0,0,1
OPCs_1.1_Suicide_B5_TTTGTCAGTATGCTTG,1,0,0,1,0,0,0,0,0,0,...,0,0,0,1,0,1,0,0,0,0
Ex_3_L4_5.1_Suicide_B5_TTTGTCAGTGGCCCTA,3,0,1,0,0,0,1,0,0,0,...,0,0,1,2,1,0,0,0,0,1
Ex_10_L2_4.1_Suicide_B5_TTTGTCATCACCCTCA,0,0,0,0,0,0,0,0,0,0,...,0,1,0,0,0,0,1,0,0,0
Ex_3_L4_5.1_Suicide_B5_TTTGTCATCTTATCTG,2,0,0,0,0,0,2,0,0,0,...,0,0,1,0,0,0,0,1,0,0

### Order based learner applied to gene expression data

In [16]:
from bayesian_order_based_learner import OrderBasedLearner

/Users/sreehari_miniravi/Work/ResearchProjects/bayesian-multi-dag/.venv/lib/python3.12/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
2026-08-16 04:02:39,366	INFO util.py:155 -- Missing packages: ['ipywidgets']. Run `pip install -U ipywidgets`, then restart the notebook server for rich notebook output.

In [17]:
# Exclude the sample with limited data
X_33 = X[:24] + X[25:]

In [18]:
p = 41
sigma_0 = np.arange(0, p)
obl_gene_expression = OrderBasedLearner(X_33, sigma_0, T=30000, verbose=True)

2026-08-16 04:02:41,131	INFO worker.py:2024 -- Started a local Ray instance.
2026-08-16 04:02:41,135	WARNING working_dir.py:91 -- Directory '__pycache__' is now ignored by default when packaging the working directory. To disable this behavior, set the `RAY_OVERRIDE_RUNTIME_ENV_DEFAULT_EXCLUDES=''` environment variable.
2026-08-16 04:02:41,139	INFO packaging.py:734 -- Creating a file package for local module '/Users/sreehari_miniravi/Work/ResearchProjects/bayesian-multi-dag/bayesian_order_based_learning'.
2026-08-16 04:02:41,142	INFO packaging.py:434 -- Pushing file package 'gcs://_ray_pkg_657919d64db8a03b.zip' (0.01MiB) to Ray cluster...
2026-08-16 04:02:41,143	INFO packaging.py:447 -- Successfully pushed file package 'gcs://_ray_pkg_657919d64db8a03b.zip'.

In [19]:
orderings, dags, log_posteriors = obl_gene_expression.compute()
obl_gene_expression.shutdown()

MCMC Sampling wth R2R:   0%|          | 12/30000 [00:00<14:04, 35.50it/s]/Users/sreehari_miniravi/Work/ResearchProjects/bayesian-multi-dag/bayesian_order_based_learning/bayesian_order_based_learner.py:96: RuntimeWarning: overflow encountered in exp
  a = min(np.exp(pi_sigma_curr - pi_sigma_prev), 1)
MCMC Sampling wth R2R:   0%|          | 34/30000 [00:26<6:25:19,  1.30it/s]

KeyboardInterrupt:

In [21]:
import pickle

data = {
    "orderings": orderings,
    "dags": dags,
    "log_posteriors": log_posteriors
}

with open(os.path.join(data_path_rel, "gene_expression_results.pkl"), "wb") as f:
    pickle.dump(data, f)

NameError: name 'orderings' is not defined

In [22]:
data = {}
with open(os.path.join(data_path_rel, "gene_expression_results.pkl"), "rb") as f:
    data = pickle.load(f)

In [23]:
orderings = data["orderings"]
dags = data["dags"]
log_posteriors = data["log_posteriors"]

In [ ]:
i = 32

In [ ]:
X_33[i]

In [ ]:
patient_dfs[i+1][1]

### Evaluating genes

In [24]:
case_patient_idx = [0, 3, 4, 5, 7, 9, 10, 13, 16, 17, 22, 24, 26, 28, 30, 31, 32]
control_patient_idx = [1, 2, 6, 8, 11, 12, 14, 15, 18, 19, 20, 21, 23, 25, 27, 29]

In [25]:
from metrics import edge_probability

K = 33
p = 41

dags_markov_chain = [[] for _ in range(K)]
adj_matrices_markov_chain = [[] for _ in range(K)]
for dag_t in dags:
    for k, dag in enumerate(dag_t):
        dags_markov_chain[k].append(dag)
        adj_matrices_markov_chain[k].append(nx.to_numpy_array(dag, weight=None, dtype=np.dtype(int)))

connectivity_case = np.zeros(p)
connectivity_control = np.zeros(p)
for k in range(K):
    adj_matrices = np.array(adj_matrices_markov_chain[k])

    for node in range(p):
        connectivity = 0
        for other_node in range(p):
            if other_node == node:
                continue

            connectivity += edge_probability(adj_matrices, (node, other_node))
            connectivity += edge_probability(adj_matrices, (other_node, node))

        if k in case_patient_idx:
            connectivity_case[node] += connectivity
        else:
            connectivity_control[node] += connectivity

connectivity_case = connectivity_case / (len(case_patient_idx))
connectivity_control = connectivity_control / (len(control_patient_idx))

"""
for dag_t in dags:
    for k, dag in enumerate(dag_t):
        adj_matrices = np.array(adj_matrices_markov_chain[k])
        for node in range(p):
            for in_edge in dag.in_edges(node):
                if k in case_patient_idx:
                    connectivity_case[node] += edge_probability(adj_matrices, in_edge)
                else:
                    connectivity_control[node] += edge_probability(adj_matrices, in_edge)

            for out_edge in dag.out_edges(node):
                if k in case_patient_idx:
                    connectivity_case[node] += edge_probability(adj_matrices, out_edge)
                else:
                    connectivity_control[node] += edge_probability(adj_matrices, out_edge)

connectivity_case = connectivity_case / (len(case_patient_idx))
connectivity_control = connectivity_control / (len(control_patient_idx))
"""

'\nfor dag_t in dags:\n    for k, dag in enumerate(dag_t):\n        adj_matrices = np.array(adj_matrices_markov_chain[k])\n        for node in range(p):\n            for in_edge in dag.in_edges(node):\n                if k in case_patient_idx:\n                    connectivity_case[node] += edge_probability(adj_matrices, in_edge)\n                else:\n                    connectivity_control[node] += edge_probability(adj_matrices, in_edge)\n\n            for out_edge in dag.out_edges(node):\n                if k in case_patient_idx:\n                    connectivity_case[node] += edge_probability(adj_matrices, out_edge)\n                else:\n                    connectivity_control[node] += edge_probability(adj_matrices, out_edge)\n\nconnectivity_case = connectivity_case / (len(case_patient_idx))\nconnectivity_control = connectivity_control / (len(control_patient_idx))\n'

In [26]:
group_diff = connectivity_control - connectivity_case
idx_diff = {idx: group_diff[idx] for idx in range(len(group_diff))}
top_20 = dict(sorted(idx_diff.items(), key=lambda item: item[1], reverse=True)[:20])
top_9 = dict(sorted(idx_diff.items(), key=lambda item: item[1], reverse=True)[:9])

mapping_dict = top_41_genes.set_index('idx')["Gene"].to_dict()

top_20 = {
    mapping_dict[idx]: value
    for idx, value in top_20.items()
    if idx in mapping_dict
}

top_9 = {
    mapping_dict[idx]: value
    for idx, value in top_9.items()
    if idx in mapping_dict
}

In [27]:
top_20

{'TUBB4B': np.float64(0.6530713235294123),
 'RAB11B': np.float64(0.505650980392157),
 'ARL8A': np.float64(0.42762156862745115),
 'PRAF2': np.float64(0.3587394607843135),
 'PTOV1': np.float64(0.34925318627450963),
 'ACAA1': np.float64(0.3353183823529413),
 'NRXN2': np.float64(0.3123848039215691),
 'PPME1': np.float64(0.2778958333333339),
 'RPS11': np.float64(0.25330784313725463),
 'TAPBP': np.float64(0.24848186274509754),
 'PEBP1': np.float64(0.2439968137254871),
 'CAMK2N2': np.float64(0.23197524509803968),
 'TMEM132A': np.float64(0.2306749999999993),
 'ADORA1': np.float64(0.20590367647058772),
 'KLC2': np.float64(0.19761372549019507),
 'ALDOA': np.float64(0.18006593137255011),
 'PINK1': np.float64(0.17005882352941182),
 'MAP2K7': np.float64(0.1237051470588244),
 'CCDC130': np.float64(0.1070301470588233),
 'CEND1': np.float64(0.10170710784313819)}

In [28]:
top_9

{'TUBB4B': np.float64(0.6530713235294123),
 'RAB11B': np.float64(0.505650980392157),
 'ARL8A': np.float64(0.42762156862745115),
 'PRAF2': np.float64(0.3587394607843135),
 'PTOV1': np.float64(0.34925318627450963),
 'ACAA1': np.float64(0.3353183823529413),
 'NRXN2': np.float64(0.3123848039215691),
 'PPME1': np.float64(0.2778958333333339),
 'RPS11': np.float64(0.25330784313725463)}

In [29]:
top_9_paper = ["GRIN2A", "CCND1", "PRKAR1B", "PEBP1", "HSP90AA1", "NRXN2", "ALDOA", "TMSB4X", "TOMIL1"]

top_9_common = {
    idx: value
    for idx, value in top_9.items()
    if idx in top_9_paper
}

In [30]:
top_9_common

{'NRXN2': np.float64(0.3123848039215691)}